FROM            node:18

LABEL           author="cofob" maintainer="cofob@riseup.net"
LABEL           org.opencontainers.image.source="https://github.com/cofob/containers"

RUN             npm install -g wrangler
