name: Build Docker containers

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: 0 0 */10 * *

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Set up script
      run: |
        wget https://gist.githubusercontent.com/cofob/b305d54ff21064eaa4f4194895c9a763/raw/list.py
    - name: Add matrix jobs
      id: set-matrix
      run: |
        JSON=`python3 list.py`
        echo $JSON
        echo "::set-output name=matrix::$JSON"
  pack:
    needs: setup
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        path: ${{fromJson(needs.setup.outputs.matrix)}}
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.PAT }}
    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.HUB }}
    - name: Build and push
      run: |
        cd ${{ matrix.path }}
        bash build.sh
